// Package cleanliness implements `aag clean check` — Wave 4 #15
// (= reposteward-ai-ops-platform、Cleanliness rules detection)。
//
// repo の placement / cleanliness 規約違反を read-only で articulate する
// detector layer。AI session が generated/ に hand-authored doc を混入したり、
// projects/completed/ に archive.manifest.json なしで archive したりする pattern を
// 検出する。
//
// 不可侵原則 (= projects/active/reposteward-ai-ops-platform/plan.md §不可侵原則):
//   1. JSON-first (= output は schema 準拠 JSON)
//   3. Read-only first (= file 走査のみ、書き換えなし)
//   5. DetectorResult-first (= 既存 DetectorResult contract と同 family の articulate)
package cleanliness

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// CheckOutput is the JSON shape emitted by `aag clean check`.
type CheckOutput struct {
	SchemaVersion string         `json:"schemaVersion"`
	Violations    []Violation    `json:"violations"`
	Stats         map[string]int `json:"stats"`
	Summary       string         `json:"summary"`
}

// Violation articulates a single cleanliness rule violation.
type Violation struct {
	Kind     string `json:"kind"`
	Path     string `json:"path"`
	Reason   string `json:"reason"`
	Severity string `json:"severity"` // "warn" or "error"
	Action   string `json:"action,omitempty"`
}

// CheckSchemaVersion is the const articulated in CheckOutput.
const CheckSchemaVersion = "clean-check-v1"

// Severity values (= AAG governance idiom 整合)。
const (
	SeverityWarn  = "warn"
	SeverityError = "error"
)

// Violation kinds.
const (
	KindGeneratedHandAuthored  = "generated-handauthored"
	KindArchiveMissingManifest = "archive-missing-manifest"
	KindProjectIdDuplicate     = "projectid-duplicate"
	KindGeneratedNoMetadata    = "generated-no-metadata"
)

// CheckInput controls Check.
type CheckInput struct {
	RepoRoot string
}

// Check scans the repo for cleanliness rule violations and returns aggregated
// findings. Always succeeds (= violations are articulated in output, never
// raised as Go error). Errors only on input / IO failure.
func Check(input CheckInput) (CheckOutput, error) {
	if input.RepoRoot == "" {
		return CheckOutput{}, fmt.Errorf("Check: RepoRoot must be set")
	}

	violations := []Violation{}
	stats := map[string]int{}

	// Rule 1: generated-handauthored
	v1 := scanGeneratedDirs(input.RepoRoot)
	violations = append(violations, v1...)
	stats[KindGeneratedHandAuthored] = len(v1)

	// Rule 2: archive-missing-manifest
	v2 := scanCompletedProjects(input.RepoRoot)
	violations = append(violations, v2...)
	stats[KindArchiveMissingManifest] = len(v2)

	// Rule 3: projectid-duplicate
	v3 := scanProjectIdDuplicates(input.RepoRoot)
	violations = append(violations, v3...)
	stats[KindProjectIdDuplicate] = len(v3)

	stats["total"] = len(violations)

	return CheckOutput{
		SchemaVersion: CheckSchemaVersion,
		Violations:    violations,
		Stats:         stats,
		Summary:       summarize(stats),
	}, nil
}

func summarize(stats map[string]int) string {
	total := stats["total"]
	if total == 0 {
		return "Repository cleanliness check: 0 violations. ✓"
	}
	parts := []string{}
	for _, k := range []string{KindGeneratedHandAuthored, KindArchiveMissingManifest, KindProjectIdDuplicate, KindGeneratedNoMetadata} {
		if c := stats[k]; c > 0 {
			parts = append(parts, fmt.Sprintf("%s=%d", k, c))
		}
	}
	return fmt.Sprintf("%d violation(s): %s", total, strings.Join(parts, ", "))
}

// ───────────────────────────────────────────────────────────────────────
// Rule 1: generated-handauthored
// ───────────────────────────────────────────────────────────────────────

// generatedDirs articulates the canonical generated artifact dirs。各 file は
// 機械生成 marker (= GENERATED:START / 機械生成 / auto-generated 等) を持つことを期待。
var generatedDirs = []string{
	"references/04-tracking/generated",
	"docs/generated",
}

// generatedMarkers articulates string patterns that indicate a file is machine-generated.
//
// MD: `> Generated:` / `> 生成:` / `機械生成` / `auto-generated` / `自動生成` /
//     `<!-- GENERATED:START` / `docs:generate` / `generated by`
// JSON: `"generatedAt"` / `"timestamp"` / `"$schemaDescription"` / `"$schema"`
var generatedMarkers = []string{
	"GENERATED:START",
	"GENERATED:END",
	"機械生成",
	"auto-generated",
	"自動生成",
	"docs:generate",
	"generated by",
	"GENERATED BY",
	"> Generated:",
	"> 生成:",
	`"generatedAt"`,
	`"timestamp"`,
	`"$schemaDescription"`,
}

func scanGeneratedDirs(repoRoot string) []Violation {
	out := []Violation{}
	for _, dir := range generatedDirs {
		abs := filepath.Join(repoRoot, dir)
		_ = filepath.WalkDir(abs, func(path string, d os.DirEntry, err error) error {
			if err != nil || d.IsDir() {
				return nil
			}
			rel, _ := filepath.Rel(repoRoot, path)
			rel = filepath.ToSlash(rel)
			// Only check .md and .json files
			if !strings.HasSuffix(rel, ".md") && !strings.HasSuffix(rel, ".json") {
				return nil
			}
			// Skip README.md — these are typically hand-authored entry docs articulating the dir
			if filepath.Base(rel) == "README.md" {
				return nil
			}
			// Convention-based pass: *.generated.md files are by definition
			// machine-generated regardless of content
			base := filepath.Base(rel)
			if strings.HasSuffix(base, ".generated.md") {
				return nil
			}
			content, err := os.ReadFile(path)
			if err != nil {
				return nil
			}
			head := head4096(content)
			if !hasGeneratedMarker(head) {
				out = append(out, Violation{
					Kind:     KindGeneratedHandAuthored,
					Path:     rel,
					Reason:   "file in generated/ dir lacks generation marker (= GENERATED:START / 機械生成 / auto-generated / generatedAt / *.generated.md suffix / etc.)",
					Severity: SeverityWarn,
					Action:   "Add a generation marker to the file header, OR rename to *.generated.md, OR move the file out of generated/ if it is hand-authored",
				})
			}
			return nil
		})
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out
}

func head4096(b []byte) string {
	if len(b) > 4096 {
		b = b[:4096]
	}
	return string(b)
}

func hasGeneratedMarker(s string) bool {
	for _, m := range generatedMarkers {
		if strings.Contains(s, m) {
			return true
		}
	}
	return false
}

// ───────────────────────────────────────────────────────────────────────
// Rule 2: archive-missing-manifest
// ───────────────────────────────────────────────────────────────────────

func scanCompletedProjects(repoRoot string) []Violation {
	out := []Violation{}
	dir := filepath.Join(repoRoot, "projects", "completed")
	entries, err := os.ReadDir(dir)
	if err != nil {
		return out
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		// Some completed projects use Archive v1 (= directory全体維持) and don't
		// have archive.manifest.json. Only flag if the directory has archiveVersion 2
		// indicators OR if there's an ARCHIVE.md file (= v2 idiom)。
		archiveMd := filepath.Join(dir, e.Name(), "ARCHIVE.md")
		manifest := filepath.Join(dir, e.Name(), "archive.manifest.json")
		if _, err := os.Stat(archiveMd); err == nil {
			// v2 idiom: must have manifest
			if _, err := os.Stat(manifest); err != nil {
				rel, _ := filepath.Rel(repoRoot, manifest)
				out = append(out, Violation{
					Kind:     KindArchiveMissingManifest,
					Path:     filepath.ToSlash(rel),
					Reason:   fmt.Sprintf("projects/completed/%s/ has ARCHIVE.md (= Archive v2 idiom) but archive.manifest.json missing", e.Name()),
					Severity: SeverityError,
					Action:   "Add archive.manifest.json articulating archiveVersion=2 + decisionEntries + commitLineage + restoreAllCommand (cf. projects/completed/aag-engine-go-mvp/archive.manifest.json)",
				})
			}
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out
}

// ───────────────────────────────────────────────────────────────────────
// Rule 3: projectid-duplicate
// ───────────────────────────────────────────────────────────────────────

func scanProjectIdDuplicates(repoRoot string) []Violation {
	out := []Violation{}
	activeDir := filepath.Join(repoRoot, "projects", "active")
	completedDir := filepath.Join(repoRoot, "projects", "completed")

	active := readDirNames(activeDir)
	completed := readDirNames(completedDir)

	for _, id := range active {
		if id == "_template" || id == "quick-fixes" {
			// quick-fixes is a long-running collection; not a duplicate concern
			continue
		}
		for _, c := range completed {
			if c == id {
				out = append(out, Violation{
					Kind:     KindProjectIdDuplicate,
					Path:     fmt.Sprintf("projects/active/%s + projects/completed/%s", id, id),
					Reason:   fmt.Sprintf("project id %q exists in both projects/active/ and projects/completed/", id),
					Severity: SeverityError,
					Action:   "Move the active project to a different id, OR delete the duplicate completed entry if it is stale",
				})
				break
			}
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out
}

func readDirNames(absDir string) []string {
	entries, err := os.ReadDir(absDir)
	if err != nil {
		return nil
	}
	out := make([]string, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() {
			out = append(out, e.Name())
		}
	}
	return out
}
