// clean_test.go — Wave 4 #15 (= reposteward-ai-ops-platform、aag clean check)
package cleanliness

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func repoRoot(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	return filepath.Join(filepath.Dir(thisFile), "..", "..", "..")
}

func TestCheck_RejectsEmptyInput(t *testing.T) {
	if _, err := Check(CheckInput{}); err == nil {
		t.Error("expected error for empty input")
	}
}

func TestCheck_RealRepo_StatsFormat(t *testing.T) {
	out, err := Check(CheckInput{RepoRoot: repoRoot(t)})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if out.SchemaVersion != CheckSchemaVersion {
		t.Errorf("schemaVersion = %q", out.SchemaVersion)
	}
	if out.Stats == nil {
		t.Error("Stats must be non-nil")
	}
	if _, ok := out.Stats["total"]; !ok {
		t.Error("Stats.total must be articulated")
	}
	if out.Summary == "" {
		t.Error("Summary must be non-empty")
	}
}

func TestHasGeneratedMarker(t *testing.T) {
	cases := []struct {
		text string
		want bool
	}{
		{"<!-- GENERATED:START -->", true},
		{"# 機械生成 docs", true},
		{"// auto-generated by tool", true},
		{"  \"generatedAt\": \"2026-...\",", true},
		{"# Hand-authored doc with no marker", false},
		{"some random text", false},
	}
	for _, tc := range cases {
		t.Run(tc.text, func(t *testing.T) {
			got := hasGeneratedMarker(tc.text)
			if got != tc.want {
				t.Errorf("got %v, want %v for %q", got, tc.want, tc.text)
			}
		})
	}
}

func TestScanGeneratedDirs_SyntheticHandauthored(t *testing.T) {
	tmp := t.TempDir()
	gen := filepath.Join(tmp, "references", "04-tracking", "generated")
	if err := os.MkdirAll(gen, 0o755); err != nil {
		t.Fatal(err)
	}
	// hand-authored .md without marker
	bad := filepath.Join(gen, "rogue.md")
	if err := os.WriteFile(bad, []byte("# Rogue Doc\n\nHand-authored without marker."), 0o644); err != nil {
		t.Fatal(err)
	}
	// machine-generated with marker
	good := filepath.Join(gen, "ok.md")
	if err := os.WriteFile(good, []byte("<!-- GENERATED:START -->\n# OK\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// README skip
	readme := filepath.Join(gen, "README.md")
	if err := os.WriteFile(readme, []byte("# Index of generated dir."), 0o644); err != nil {
		t.Fatal(err)
	}

	out := scanGeneratedDirs(tmp)
	if len(out) != 1 {
		t.Errorf("expected 1 violation, got %d: %v", len(out), out)
	}
	if len(out) > 0 && !strings.Contains(out[0].Path, "rogue.md") {
		t.Errorf("expected rogue.md flagged, got: %s", out[0].Path)
	}
}

func TestScanCompletedProjects_MissingManifest(t *testing.T) {
	tmp := t.TempDir()
	bad := filepath.Join(tmp, "projects", "completed", "bad-project")
	if err := os.MkdirAll(bad, 0o755); err != nil {
		t.Fatal(err)
	}
	// Has ARCHIVE.md (= v2 idiom) but no manifest
	if err := os.WriteFile(filepath.Join(bad, "ARCHIVE.md"), []byte("# Archive"), 0o644); err != nil {
		t.Fatal(err)
	}

	good := filepath.Join(tmp, "projects", "completed", "good-project")
	if err := os.MkdirAll(good, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(good, "ARCHIVE.md"), []byte("# Archive"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(good, "archive.manifest.json"), []byte("{}"), 0o644); err != nil {
		t.Fatal(err)
	}

	v1Project := filepath.Join(tmp, "projects", "completed", "v1-project")
	if err := os.MkdirAll(v1Project, 0o755); err != nil {
		t.Fatal(err)
	}
	// v1: no ARCHIVE.md, just regular dirs — should NOT be flagged
	if err := os.WriteFile(filepath.Join(v1Project, "AI_CONTEXT.md"), []byte("# v1 archive style"), 0o644); err != nil {
		t.Fatal(err)
	}

	out := scanCompletedProjects(tmp)
	if len(out) != 1 {
		t.Errorf("expected 1 violation (bad-project only), got %d: %v", len(out), out)
	}
	if len(out) > 0 && !strings.Contains(out[0].Path, "bad-project") {
		t.Errorf("expected bad-project flagged, got: %s", out[0].Path)
	}
}

func TestScanProjectIdDuplicates_Synthetic(t *testing.T) {
	tmp := t.TempDir()
	if err := os.MkdirAll(filepath.Join(tmp, "projects", "active", "shared-id"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(tmp, "projects", "completed", "shared-id"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(tmp, "projects", "active", "unique-id"), 0o755); err != nil {
		t.Fatal(err)
	}

	out := scanProjectIdDuplicates(tmp)
	if len(out) != 1 {
		t.Errorf("expected 1 violation (shared-id), got %d", len(out))
	}
}

func TestScanProjectIdDuplicates_QuickFixesNotFlagged(t *testing.T) {
	tmp := t.TempDir()
	if err := os.MkdirAll(filepath.Join(tmp, "projects", "active", "quick-fixes"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(tmp, "projects", "completed", "quick-fixes"), 0o755); err != nil {
		t.Fatal(err)
	}

	out := scanProjectIdDuplicates(tmp)
	if len(out) != 0 {
		t.Errorf("quick-fixes should not flag duplicate, got %d violations", len(out))
	}
}

func TestSummarize_Empty(t *testing.T) {
	got := summarize(map[string]int{"total": 0})
	if !strings.Contains(got, "0 violations") {
		t.Errorf("zero summary unexpected: %q", got)
	}
}

func TestSummarize_WithViolations(t *testing.T) {
	got := summarize(map[string]int{
		"total":                          3,
		KindGeneratedHandAuthored:        2,
		KindArchiveMissingManifest:       1,
	})
	if !strings.Contains(got, "3 violation") {
		t.Errorf("summary count missing: %q", got)
	}
}
